docker

diff --git a/docker/files/firstboot/functions b/docker/files/firstboot/functions
--- a/docker/files/firstboot/functions
+++ b/docker/files/firstboot/functions
@@ -91,18 +91,18 @@ core3_mysql_setup() {
 
     msg "Init mysql database"
     chown -R mysql:mysql /var/lib/mysql /var/lib/mysql/.
-    mysql_install_db
+    #mysql_install_db
     chown -R mysql:mysql /var/lib/mysql /var/lib/mysql/.
-    /etc/init.d/mariadb start
-    # mkdir -p /var/run/mysqld
-    # mkdir -p /var/lib/mysql
-    # chown -R mysql:mysql /var/run/mysqld
-    # chown -R mysql:mysql /var/lib/mysql
-    # chmod 777 /var/run/mysqld
+    #/etc/init.d/mariadb start
+    mkdir -p /var/run/mysqld
+    mkdir -p /var/lib/mysql
+    chown -R mysql:mysql /var/run/mysqld
+    chown -R mysql:mysql /var/lib/mysql
+    chmod 777 /var/run/mysqld
 
-    # mysql_install_db --user=mysql --basedir=/usr --datadir=/var/lib/mysql
-    # mysqld_safe --datadir='/var/lib/mysql' &
-    # sleep 5
+    mysql_install_db --user=mysql --basedir=/usr --datadir=/var/lib/mysql
+    mysqld_safe --datadir='/var/lib/mysql' &
+    sleep 5
 
     mysql -v <<-EOF
         SET @@SESSION.SQL_LOG_BIN=0;
@@ -121,8 +121,7 @@ EOF
 
     if [ -f "${init_sql}" ]; then
         msg "Create database from ${init_sql}"
-        core3_mysql_fix_dbname "${init_sql}" | mysql || error "Failed to run swgemu.sql" 12
-        #core3_mysql_fix_dbname "${init_sql}" | mysql -uroot -p"${DBPASS}" || error "Failed to run swgemu.sql" 12
+        core3_mysql_fix_dbname "${init_sql}" | mysql -uroot -p"${DBPASS}" || error "Failed to run swgemu.sql" 12
     else
         warning "Failed to find ${init_sql} file to setup the database"
     fi
